import { createServerFn } from '@tanstack/react-start'
import type { Machine } from '../lib/types'

/**
 * Fetch machine status. Priority:
 * 1. Tailscale API (production — needs TAILSCALE_API_KEY)
 * 2. Local snapshot file (dev — generated by scripts/tailscale-snapshot.sh)
 * 3. Static fallback
 */
export const getMachines = createServerFn().handler(async (): Promise<Machine[]> => {
  // Try Tailscale API first (production)
  const apiKey = process.env.TAILSCALE_API_KEY
  if (apiKey) {
    try {
      const machines = await fetchFromTailscaleApi(apiKey)
      if (machines.length > 0) return machines
    } catch (err) {
      console.error('Tailscale API error:', err)
    }
  }

  // Try snapshot file (dev mode — written by scripts/tailscale-snapshot.sh)
  try {
    const snapshot = await fetchSnapshot()
    if (snapshot.length > 0) return snapshot
  } catch {
    // Snapshot not available
  }

  return fallbackMachines()
})

async function fetchFromTailscaleApi(apiKey: string): Promise<Machine[]> {
  const res = await fetch('https://api.tailscale.com/api/v2/tailnet/-/devices', {
    headers: { Authorization: `Bearer ${apiKey}` },
  })

  if (!res.ok) throw new Error(`Tailscale API: ${res.status}`)

  const data = (await res.json()) as { devices: TailscaleDevice[] }

  return data.devices
    .filter((d) => !d.isExternal)
    .map((d) => ({
      hostname: d.hostname || d.name.split('.')[0],
      os: d.os || 'unknown',
      status: d.online ? 'online' : 'offline',
      ip: d.addresses?.[0] || '',
      tasks: 0,
      lastSeen: d.lastSeen,
    }))
}

async function fetchSnapshot(): Promise<Machine[]> {
  // In dev, the snapshot is in public/ and served as a static file
  // In production, this would come from D1 or a heartbeat API
  const res = await fetch('http://localhost:3000/tailscale-status.json')
  if (!res.ok) return []
  const data = (await res.json()) as { machines: Machine[] }
  return data.machines
}

interface TailscaleDevice {
  name: string
  hostname: string
  os: string
  online: boolean
  addresses: string[]
  lastSeen: string
  isExternal?: boolean
}

function fallbackMachines(): Machine[] {
  return [
    { hostname: 'providence', os: 'macOS', status: 'online', ip: '100.84.211.58', tasks: 0 },
    { hostname: 'destiny', os: 'macOS', status: 'offline', ip: '100.84.253.65', tasks: 0 },
    { hostname: 'stargate', os: 'Windows', status: 'online', ip: '100.107.60.12', tasks: 0 },
    { hostname: 'stargate-wsl', os: 'Linux', status: 'online', ip: '100.92.249.32', tasks: 0 },
  ]
}
