import type { BriefingItem } from "../lib/briefing";
import type { DataSource, DataSourceConfig } from "../lib/datasource";

/**
 * Market Insights - AI-detected opportunities and threats
 *
 * Shows unaddressed market gaps, threats, opportunities, and trends
 * identified by Claude during weekly/monthly analysis jobs.
 *
 * Generated by:
 * - Claude API: Analyzes competitive changes for strategic insights
 * - Heuristic detection: Automated threshold-based findings
 * - Manual input: Strategic team contributions
 */
export const marketInsightsSource: DataSource = {
	id: "market-insights",
	name: "Market Opportunities",
	icon: "💡",
	description: "AI-detected market gaps and competitive opportunities",
	requiresConfig: false,

	async fetch(config: DataSourceConfig): Promise<BriefingItem[]> {
		// In Week 1: Return setup status
		// In Week 2+: Query market_insights table from D1
		// Show high-confidence opportunities and threats

		return [{
			id: "market-insights-ready",
			priority: "normal",
			category: "status",
			title: "Market Insights",
			detail: "AI analysis begins Week 3. Opportunities will appear here daily.",
			time: new Date().toISOString(),
		}];
	},
};
