/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandsSlugRouteImport } from './routes/brands/$slug'
import { Route as ApiWsRouteImport } from './routes/api/ws'
import { Route as ApiOrchestrateRouteImport } from './routes/api/orchestrate'
import { Route as ApiOnboardingRouteImport } from './routes/api/onboarding'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsSlugRoute = BrandsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BrandsRoute,
} as any)
const ApiWsRoute = ApiWsRouteImport.update({
  id: '/api/ws',
  path: '/api/ws',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrchestrateRoute = ApiOrchestrateRouteImport.update({
  id: '/api/orchestrate',
  path: '/api/orchestrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingRoute = ApiOnboardingRouteImport.update({
  id: '/api/onboarding',
  path: '/api/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/onboarding': typeof ApiOnboardingRoute
  '/api/orchestrate': typeof ApiOrchestrateRoute
  '/api/ws': typeof ApiWsRoute
  '/brands/$slug': typeof BrandsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/onboarding': typeof ApiOnboardingRoute
  '/api/orchestrate': typeof ApiOrchestrateRoute
  '/api/ws': typeof ApiWsRoute
  '/brands/$slug': typeof BrandsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brands': typeof BrandsRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/onboarding': typeof ApiOnboardingRoute
  '/api/orchestrate': typeof ApiOrchestrateRoute
  '/api/ws': typeof ApiWsRoute
  '/brands/$slug': typeof BrandsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brands'
    | '/login'
    | '/onboarding'
    | '/api/chat'
    | '/api/onboarding'
    | '/api/orchestrate'
    | '/api/ws'
    | '/brands/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brands'
    | '/login'
    | '/onboarding'
    | '/api/chat'
    | '/api/onboarding'
    | '/api/orchestrate'
    | '/api/ws'
    | '/brands/$slug'
  id:
    | '__root__'
    | '/'
    | '/brands'
    | '/login'
    | '/onboarding'
    | '/api/chat'
    | '/api/onboarding'
    | '/api/orchestrate'
    | '/api/ws'
    | '/brands/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandsRoute: typeof BrandsRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiOnboardingRoute: typeof ApiOnboardingRoute
  ApiOrchestrateRoute: typeof ApiOrchestrateRoute
  ApiWsRoute: typeof ApiWsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$slug': {
      id: '/brands/$slug'
      path: '/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof BrandsSlugRouteImport
      parentRoute: typeof BrandsRoute
    }
    '/api/ws': {
      id: '/api/ws'
      path: '/api/ws'
      fullPath: '/api/ws'
      preLoaderRoute: typeof ApiWsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orchestrate': {
      id: '/api/orchestrate'
      path: '/api/orchestrate'
      fullPath: '/api/orchestrate'
      preLoaderRoute: typeof ApiOrchestrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding': {
      id: '/api/onboarding'
      path: '/api/onboarding'
      fullPath: '/api/onboarding'
      preLoaderRoute: typeof ApiOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BrandsRouteChildren {
  BrandsSlugRoute: typeof BrandsSlugRoute
}

const BrandsRouteChildren: BrandsRouteChildren = {
  BrandsSlugRoute: BrandsSlugRoute,
}

const BrandsRouteWithChildren =
  BrandsRoute._addFileChildren(BrandsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandsRoute: BrandsRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiChatRoute: ApiChatRoute,
  ApiOnboardingRoute: ApiOnboardingRoute,
  ApiOrchestrateRoute: ApiOrchestrateRoute,
  ApiWsRoute: ApiWsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
