/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiThreadsRouteImport } from './routes/api/threads'
import { Route as ApiOrchestrateRouteImport } from './routes/api/orchestrate'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThreadsRoute = ApiThreadsRouteImport.update({
  id: '/api/threads',
  path: '/api/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrchestrateRoute = ApiOrchestrateRouteImport.update({
  id: '/api/orchestrate',
  path: '/api/orchestrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/orchestrate': typeof ApiOrchestrateRoute
  '/api/threads': typeof ApiThreadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/orchestrate': typeof ApiOrchestrateRoute
  '/api/threads': typeof ApiThreadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/orchestrate': typeof ApiOrchestrateRoute
  '/api/threads': typeof ApiThreadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/chat' | '/api/orchestrate' | '/api/threads'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/chat' | '/api/orchestrate' | '/api/threads'
  id: '__root__' | '/' | '/api/chat' | '/api/orchestrate' | '/api/threads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiOrchestrateRoute: typeof ApiOrchestrateRoute
  ApiThreadsRoute: typeof ApiThreadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/threads': {
      id: '/api/threads'
      path: '/api/threads'
      fullPath: '/api/threads'
      preLoaderRoute: typeof ApiThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orchestrate': {
      id: '/api/orchestrate'
      path: '/api/orchestrate'
      fullPath: '/api/orchestrate'
      preLoaderRoute: typeof ApiOrchestrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiOrchestrateRoute: ApiOrchestrateRoute,
  ApiThreadsRoute: ApiThreadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
